name: total_english
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: ^0.20.2
  image_picker: ^0.8.7+5

  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  flutter_facebook_auth: ^7.1.0
  google_sign_in: ^6.3.0
  email_otp: ^3.0.2
  flutter_tts: ^4.2.2
  speech_to_text: ^7.0.0
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.13.1 #cài đặt package đổi icon
  font_awesome_flutter: ^10.7.0 # Thêm dependency FontAwesome
  waveform_flutter: ^1.2.0
  lottie: ^3.3.1
  week_of_year: ^2.2.0
  # workmanager: ^0.5.2
  easy_localization: ^3.0.1 # ✅ Đã thêm

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icon/app_icon.png
    - assets/icon/panda_icon.png
    - assets/icon/fire.json
    - assets/icon/no_background.png
    - assets/icon/bye.png
    - assets/icon/gg_light.png
    - assets/lang/ # ✅ Đã thêm thư mục ngôn ngữ

  fonts:
    - family: Kavoon
      fonts:
        - asset: assets/fonts/Kavoon-Regular.ttf
    - family: Kadwa  # Thêm Kadwa vào đây
      fonts:
        - asset: assets/fonts/Kadwa-Bold.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
